Repository SM-137/SM-137-Backend, pull requests merged in 2025-01, with the labels that each got.

#16 [feat] 관리자 / 민원 리스트 및 상세 조회 api 구현
  src/main/java/com/solux/sm137/controller/ManagerController.java
  src/main/java/com/solux/sm137/dto/response/ComplaintDetailResponse.java
  src/main/java/com/solux/sm137/dto/response/ManagerComplaintResponse.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/FailureStatus.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/SuccessStatus.java
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
Labels: ⭐ [FEAT], :recycle: [REFACTOR], :crown: 은지

#14 [feat] 회원탈퇴 api 구현
  src/main/java/com/solux/sm137/controller/UserController.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/SuccessStatus.java
  src/main/java/com/solux/sm137/service/UserService.java
Labels: ⭐ [FEAT], :crown: 은지

#20 [feat] 사용자 / 민원 상세 및 리스트 api 구현
  src/main/java/com/solux/sm137/controller/ComplaintController.java
  src/main/java/com/solux/sm137/domain/ComplaintLike.java
  src/main/java/com/solux/sm137/domain/CompositeId.java
  src/main/java/com/solux/sm137/domain/Scrap.java
  src/main/java/com/solux/sm137/dto/request/CategoryRequest.java
  src/main/java/com/solux/sm137/dto/response/CategoryResponse.java
  src/main/java/com/solux/sm137/dto/response/KeywordSearchResponse.java
  src/main/java/com/solux/sm137/dto/response/UserComplaintDetailResponse.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/SuccessStatus.java
  src/main/java/com/solux/sm137/repository/ComplaintRepository.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
Labels: ⭐ [FEAT], :wrench: [FIX], :recycle: [REFACTOR], :cherry_blossom: 은영

#18 [feat] 관리자 / 민원 답변 등록
  src/main/java/com/solux/sm137/controller/ManagerController.java
  src/main/java/com/solux/sm137/domain/Complaint.java
  src/main/java/com/solux/sm137/dto/request/ComplaintAnswerRequest.java
  src/main/java/com/solux/sm137/dto/response/ComplaintAnswerResponse.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/FailureStatus.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/SuccessStatus.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
Labels: ⭐ [FEAT], :wrench: [FIX], :crown: 은지

#19 [feat] 소셜로그인, 로그아웃 api 구현
  .gitignore
  build.gradle
  src/main/java/com/solux/sm137/controller/AuthController.java
  src/main/java/com/solux/sm137/domain/User.java
  src/main/java/com/solux/sm137/dto/request/OAuthAttributes.java
  src/main/java/com/solux/sm137/dto/response/LoginResponse.java
  src/main/java/com/solux/sm137/dto/response/SessionUser.java
  src/main/java/com/solux/sm137/infra/BaseTimeEntity.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/SuccessStatus.java
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
  src/main/java/com/solux/sm137/repository/UserRepository.java
  src/main/java/com/solux/sm137/service/CustomOAuth2UserService.java
Labels: ⭐ [FEAT], :crown: 은지

#25 [feat] 스크랩취소 api 구현
  src/main/java/com/solux/sm137/controller/ComplaintController.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/SuccessStatus.java
  src/main/java/com/solux/sm137/repository/ScrapRepository.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
Labels: ⭐ [FEAT], :cherry_blossom: 은영

#29 [feat] swagger 추가 및 코드 정리
  build.gradle
  src/main/java/com/solux/sm137/controller/AuthController.java
  src/main/java/com/solux/sm137/controller/ComplaintController.java
  src/main/java/com/solux/sm137/controller/ManagerController.java
  src/main/java/com/solux/sm137/controller/UserController.java
  src/main/java/com/solux/sm137/dto/request/OAuthAttributes.java
  src/main/java/com/solux/sm137/dto/response/ManagerComplaintResponse.java
  src/main/java/com/solux/sm137/dto/response/MyComplaintResponse.java
  src/main/java/com/solux/sm137/dto/response/ResultResponse.java
  src/main/java/com/solux/sm137/dto/response/ScrapResponse.java
  src/main/java/com/solux/sm137/dto/response/UserComplaintDetailResponse.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/FailureStatus.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/SuccessStatus.java
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
  src/main/java/com/solux/sm137/infra/config/SwaggerConfig.java
Labels: ⭐ [FEAT], :fallen_leaf: 가을

#31 [refactor] 소셜 로그인 api 수정
  build.gradle
  src/main/java/com/solux/sm137/controller/AuthController.java
  src/main/java/com/solux/sm137/domain/User.java
  src/main/java/com/solux/sm137/dto/request/OAuthAttributes.java
  src/main/java/com/solux/sm137/dto/response/SessionUser.java
  src/main/java/com/solux/sm137/infra/apiPayload/handler/OAuth2SuccessHandler.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/FailureStatus.java
  src/main/java/com/solux/sm137/infra/common/jwt/JwtTokenProvider.java
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
  src/main/java/com/solux/sm137/service/CustomOAuth2UserService.java
  src/main/resources/static/favicon.ico
Labels: :recycle: [REFACTOR], :crown: 은지

#33 [add] response 해시태그 추가
  src/main/java/com/solux/sm137/dto/response/CategoryResponse.java
  src/main/java/com/solux/sm137/dto/response/UserComplaintDetailResponse.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
Labels: ➕ [ADD], :cherry_blossom: 은영

#34 [mod] jwt 토큰으로 유저 찾는 로직 추가
  src/main/java/com/solux/sm137/Application.java
  src/main/java/com/solux/sm137/controller/AuthController.java
  src/main/java/com/solux/sm137/controller/ComplaintController.java
  src/main/java/com/solux/sm137/controller/UserController.java
  src/main/java/com/solux/sm137/infra/common/jwt/JwtTokenProvider.java
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
  src/main/java/com/solux/sm137/repository/TagRepository.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
  src/main/java/com/solux/sm137/service/UserService.java
Labels: ✅ [MOD], :fallen_leaf: 가을

#42 [refactor] 민원api 로직 변경
  src/main/java/com/solux/sm137/controller/ComplaintController.java
  src/main/java/com/solux/sm137/dto/response/ComplaintAnswerResponse.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
Labels: :recycle: [REFACTOR], :cherry_blossom: 은영

#49 [feat] S3 연결
  build.gradle
  src/main/java/com/solux/sm137/controller/ComplaintController.java
  src/main/java/com/solux/sm137/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/solux/sm137/domain/Attachment.java
  src/main/java/com/solux/sm137/domain/Category.java
  src/main/java/com/solux/sm137/domain/CompositeId.java
  src/main/java/com/solux/sm137/dto/request/ComplaintRequest.java
  src/main/java/com/solux/sm137/dto/response/ComplaintDetailResponse.java
  src/main/java/com/solux/sm137/dto/response/ComplaintResponse.java
  src/main/java/com/solux/sm137/dto/response/UserComplaintDetailResponse.java
  src/main/java/com/solux/sm137/infra/config/AmazonConfig.java
  src/main/java/com/solux/sm137/infra/config/WebConfig.java
  src/main/java/com/solux/sm137/infra/s3/AmazonS3Manager.java
  src/main/java/com/solux/sm137/repository/AttachmentRepository.java
  src/main/java/com/solux/sm137/repository/CategoryRepository.java
  src/main/java/com/solux/sm137/service/AttachmentService.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
Labels: ⭐ [FEAT], :fallen_leaf: 가을

#51 [add] cors 허용 uri 추가
  .github/workflows/dev_deploy.yml
  build.gradle
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
Labels: ➕ [ADD], :fallen_leaf: 가을

#53 [feat] 전체 민원 조회 api 구현
  src/main/java/com/solux/sm137/controller/ComplaintController.java
  src/main/java/com/solux/sm137/dto/response/GetAllComplaintResponse.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/SuccessStatus.java
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
Labels: ⭐ [FEAT], :fallen_leaf: 가을

#55 민원 작성 중 개선방향과 기대효과 null 허용으로 변경
  build.gradle
  src/main/java/com/solux/sm137/domain/Complaint.java
Labels: ✅ [MOD], :cat: 은서

#57 [mod] complaint 최근순 정렬
  src/main/java/com/solux/sm137/repository/ComplaintRepository.java
  src/main/java/com/solux/sm137/repository/ScrapRepository.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
  src/main/java/com/solux/sm137/service/UserService.java
Labels: ✅ [MOD], :crown: 은지

#59 [fix] fe 연동
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
Labels: :wrench: [FIX]

#62 [mod] 검색쿼리 변경 및 response에 작성일 추가
  src/main/java/com/solux/sm137/controller/ComplaintController.java
  src/main/java/com/solux/sm137/dto/request/CategoryRequest.java
  src/main/java/com/solux/sm137/dto/response/CategoryResponse.java
  src/main/java/com/solux/sm137/dto/response/GetAllComplaintResponse.java
  src/main/java/com/solux/sm137/repository/ComplaintRepository.java
  src/main/java/com/solux/sm137/service/ComplaintService.java
Labels: ✅ [MOD], :cherry_blossom: 은영

#64 [mod] jwt token 반환 코드 수정
  src/main/java/com/solux/sm137/infra/apiPayload/handler/OAuth2SuccessHandler.java
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
Labels: ✅ [MOD]

#65 [mod] cors 주소 변경
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
Labels: ✅ [MOD], :crown: 은지

#66 [mod] 소셜로그인 리디렉션 수정 및 컨트롤러 삭제
  src/main/java/com/solux/sm137/controller/AuthController.java
  src/main/java/com/solux/sm137/infra/apiPayload/handler/OAuth2SuccessHandler.java
  src/main/java/com/solux/sm137/infra/apiPayload/status/SuccessStatus.java
  src/main/java/com/solux/sm137/infra/config/SecurityConfig.java
Labels: ✅ [MOD], :x: [DEL], :crown: 은지

#67 [mod] JWT 토큰 쿠키로 전달
  src/main/java/com/solux/sm137/infra/apiPayload/handler/OAuth2SuccessHandler.java
Labels: ✅ [MOD], :crown: 은지

#68 [fix] jwtcookie 설정 변경
  src/main/java/com/solux/sm137/infra/apiPayload/handler/OAuth2SuccessHandler.java
Labels: :wrench: [FIX]

#73 [feat] KST 타임존, 댓글 좋아요 수 추가
  src/main/java/com/solux/sm137/Application.java
  src/main/java/com/solux/sm137/dto/response/CommentResponse.java
  src/main/java/com/solux/sm137/repository/CommentLikeRepository.java
  src/main/java/com/solux/sm137/service/CommentLikeService.java
  src/main/java/com/solux/sm137/service/CommentService.java
Labels: ⭐ [FEAT], :fallen_leaf: 가을

#75 [mod] redirect url 변경
  src/main/java/com/solux/sm137/infra/apiPayload/handler/OAuth2SuccessHandler.java
Labels: ✅ [MOD], :fallen_leaf: 가을
